### PR TITLE
Training framework fix

### LINKED ISSUE #24: Support max-training-framework 0.1.1
Starting with version 0.1.1, `setup_max_model_training` is only looking for training data files in the `data` subdirectory. We therefore need to
- move `sample_training_data/sample-train.json` to `sample_training_data/data/sample-train.json`
- change the model training code to load training data from `${DATA_DIR}/data`
- update the documentation
before this model can utilize 0.1.1.

### PR DESCRIPTION
**Pull request by kmh4321**
fixes #24

### CODE REVIEW

File: training/training_code/train-max-model.sh [hunk 1]
```diff
@@ -13,6 +13,7 @@ POST_PROCESSING_FAILED=2
 PACKAGING_FAILED_RETURN_CODE=3
 CUSTOMIZATION_ERROR_RETURN_CODE=4
 ENV_ERROR_RETURN_CODE=5
+DATA_DIR=${DATA_DIR}/data
```
Comment (ptitzler) [inline training/training_code/train-max-model.sh]: As implemented, this change will invalidate the check in https://github.com/IBM/MAX-Question-Answering/blob/7e3bfd4a6d7b98d1a5f6980709486e43bee12ec3/training/training_code/train-max-model.sh#L24 because the `DATA_DIR` environment variable is now always defined.

See 
following https://github.com/IBM/MAX-Text-Sentiment-Classifier/blob/master/training/training_code/train-max-model.sh#L39-L45 for a solution that shouldn't have any side effects.

**Comment by ptitzler** [comment]
... and with the fix in place we have to bump up  https://github.com/IBM/MAX-Question-Answering/blob/training-fix/training/requirements.txt#L5 to require `>=0.1`
